// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdOLo0znC4CLm_f3PY9xTSn1TuSv0dCD4',
    appId: '1:467778835730:web:e4a98f3ac751b50737cfcb',
    messagingSenderId: '467778835730',
    projectId: 'total-bts',
    authDomain: 'total-bts.firebaseapp.com',
    storageBucket: 'total-bts.firebasestorage.app',
    measurementId: 'G-0K7PMGBFES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbilVUqhwRnN5t73XcmCtL5i8M-eTTJpw',
    appId: '1:467778835730:android:ae212e8379550e3c37cfcb',
    messagingSenderId: '467778835730',
    projectId: 'total-bts',
    storageBucket: 'total-bts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4IRqpV6bU9Ok7_qTFSQkmcFDyrgWtdFM',
    appId: '1:467778835730:ios:5a23abe6be942f3d37cfcb',
    messagingSenderId: '467778835730',
    projectId: 'total-bts',
    storageBucket: 'total-bts.firebasestorage.app',
    iosBundleId: 'com.example.totalEnergies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4IRqpV6bU9Ok7_qTFSQkmcFDyrgWtdFM',
    appId: '1:467778835730:ios:5a23abe6be942f3d37cfcb',
    messagingSenderId: '467778835730',
    projectId: 'total-bts',
    storageBucket: 'total-bts.firebasestorage.app',
    iosBundleId: 'com.example.totalEnergies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdOLo0znC4CLm_f3PY9xTSn1TuSv0dCD4',
    appId: '1:467778835730:web:9bfff59bd9e4c5d937cfcb',
    messagingSenderId: '467778835730',
    projectId: 'total-bts',
    authDomain: 'total-bts.firebaseapp.com',
    storageBucket: 'total-bts.firebasestorage.app',
    measurementId: 'G-WEXJ98HTXG',
  );

}